In [1]:
import tensorflow as tf
import numpy as np
tf.config.list_physical_devices('GPU')

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [2]:
xinput = np.array([[1,2,3,4],[5,6,7,8],[1,4,6,7]], dtype=np.float)
yinput = np.array([0, 1, 2])
print(xinput)
print(yinput)

[[1. 2. 3. 4.]
 [5. 6. 7. 8.]
 [1. 4. 6. 7.]]
[0 1 2]


In [3]:
model = tf.keras.Sequential([
    tf.keras.layers.Dense(4, input_shape=(4,), activation='relu'),
    tf.keras.layers.Dense(4, activation='relu'),
    tf.keras.layers.Dense(3)
])
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)
optimizer = tf.keras.optimizers.Adam(
    learning_rate=0.01, beta_1=0.9, beta_2=0.999, epsilon=1e-07, amsgrad=False,
    name='Adam'
)
model.compile(optimizer=optimizer,
              loss=loss_fn,
              metrics='acc')

In [4]:
print(model.summary())

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 4)                 20        
_________________________________________________________________
dense_1 (Dense)              (None, 4)                 20        
_________________________________________________________________
dense_2 (Dense)              (None, 3)                 15        
Total params: 55
Trainable params: 55
Non-trainable params: 0
_________________________________________________________________
None


In [5]:
model.fit(xinput, yinput, epochs=50, batch_size=1, verbose=1)

Epoch 1/50
3/3 [==============================] - 0s 3ms/step - loss: 1.1787 - acc: 0.3333
Epoch 2/50
3/3 [==============================] - 0s 3ms/step - loss: 1.1427 - acc: 0.3333
Epoch 3/50
3/3 [==============================] - 0s 3ms/step - loss: 1.1385 - acc: 0.3333
Epoch 4/50
3/3 [==============================] - 0s 3ms/step - loss: 1.1282 - acc: 0.3333
Epoch 5/50
3/3 [==============================] - 0s 3ms/step - loss: 1.1173 - acc: 0.3333
Epoch 6/50
3/3 [==============================] - 0s 3ms/step - loss: 1.1150 - acc: 0.3333
Epoch 7/50
3/3 [==============================] - 0s 3ms/step - loss: 1.1120 - acc: 0.0000e+00
Epoch 8/50
3/3 [==============================] - 0s 3ms/step - loss: 1.1032 - acc: 0.0000e+00
Epoch 9/50
3/3 [==============================] - 0s 3ms/step - loss: 1.1020 - acc: 0.0000e+00
Epoch 10/50
3/3 [==============================] - 0s 3ms/step - loss: 1.1023 - acc: 0.0000e+00
Epoch 11/50
3/3 [==============================] - 0s 3ms/step - loss: 1.

In [6]:
xinput[:1, :]

array([[1., 2., 3., 4.]])

In [6]:
model.predict_classes(xinput[:1, :])

Instructions for updating:
Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).


array([2], dtype=int64)

In [ ]:
xinput = np.array([[]])